spring.datasource.url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11479203?useSSL=false
spring.datasource.username: sql11479203
spring.datasource.password: ipELUyPxJS
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.hibernate.ddl-auto: update
spring.datasource.initialization-mode: never
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port: ${PORT:8080}

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: passrecovery2022@gmail.com
spring.mail.password: pskiltwyolyjkskv
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

blog.title: DevTalk
blog.subtitle: Беседы разработчиков
blog.phone: +7 900 000-00-00
blog.email: red_ak@mail.ru
blog.copyright: Andrey Kuznetsov
blog.copyrightFrom: 2022

